CREATE SEQUENCE "PUBLIC"."PID" START WITH 1 INCREMENT BY 9999;
CREATE CACHED TABLE "PUBLIC"."USER"(
    "UID" VARCHAR(255) NOT NULL,
    "DISPLAY_NAME" VARCHAR(255),
    "EMAIL" VARCHAR(255),
    "EMAIL_VERIFIED" BOOLEAN NOT NULL,
    "PHOTOURL" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."TYPE_ELEMENT"(
    "NAMESPACE_ID" VARCHAR(255) NOT NULL SELECTIVITY 4,
    "SL_NO" INTEGER NOT NULL SELECTIVITY 100,
    "TYPE_ID" VARCHAR(255) NOT NULL SELECTIVITY 4,
    "ELEMENT_DESC" VARCHAR(255) SELECTIVITY 4,
    "ELEMENT_NAME" VARCHAR(255) SELECTIVITY 100,
    "ELEMENT_TYPE_ID" VARCHAR(255) SELECTIVITY 18,
    "MAX_OCCURS" VARCHAR(255) SELECTIVITY 4,
    "MIN_OCCURS" VARCHAR(255) SELECTIVITY 4
);
CREATE CACHED TABLE "PUBLIC"."TYPESREPO"(
    "NAMESPACE_ID" VARCHAR(255) NOT NULL,
    "TYPE_ID" VARCHAR(255) NOT NULL,
    "DESC" VARCHAR(255),
    "TEMPLATE_ID" VARCHAR(255),
    "TYPE" VARCHAR(255),
    "TYPE_NAME" VARCHAR(255),
    "ENUMS" VARCHAR(255),
    "MAX_OCCURS" VARCHAR(255),
    "MIN_OCCURS" VARCHAR(255),
    "PATTERN" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."TEMPLATE"(
    "TEMPLATE_ID" VARCHAR(255) NOT NULL,
    "FORMAT" INTEGER NOT NULL,
    "MAX_OCCURS" INTEGER NOT NULL,
    "MIN_OCCURS" INTEGER NOT NULL,
    "NAMESPACE_ID" VARCHAR(255),
    "PUBLISHED" BOOLEAN NOT NULL,
    "ROOTTYPE_ID" VARCHAR(255),
    "TEMPLATE_DESC" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."SWAGGER_SPEC"(
    "ID" VARCHAR(255) NOT NULL,
    "PID" VARCHAR(255) NOT NULL,
    "SPEC" CLOB
);
CREATE CACHED TABLE "PUBLIC"."SIMPLE_TYPE"(
    "NAMESPACE_ID" VARCHAR(255) NOT NULL,
    "TYPE_ID" VARCHAR(255) NOT NULL,
    "MAX_LENGTH" INTEGER NOT NULL,
    "MIN_LENGTH" INTEGER NOT NULL,
    "REGEX" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."REFFERED_TEMPLATE"(
    "REFFERED_TEMPLATE_ID" VARCHAR(255) NOT NULL,
    "TEMPLATE_ID" VARCHAR(255) NOT NULL
);
CREATE CACHED TABLE "PUBLIC"."NAMESPACEREP"(
    "NAMESPACE_ID" VARCHAR(255) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "NAMESPACE_URL" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."FILE_EXPLORER"(
    "ID" VARCHAR(255) NOT NULL,
    "PID" VARCHAR(255) NOT NULL,
    "NAME" VARCHAR(255),
    "PARENT_ID" VARCHAR(255),
    "TYPE" VARCHAR(255),
    "PATH" VARCHAR(255)
);
INSERT INTO FILE_EXPLORER(ID,PID,NAME,PARENT_ID,TYPE,PATH) VALUES('FE_0000001','','Home','','1','/Home');
CREATE CACHED TABLE "PUBLIC"."FAVOURITE"(
    "ITEMID" VARCHAR(255) NOT NULL,
    "PID" VARCHAR(255) NOT NULL,
    "USERID" VARCHAR(255) NOT NULL,
    "FILE_DETAILS_ID" VARCHAR(255),
    "FILE_DETAILS_PID" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."COMPLEX_TYPE"(
    "NAMESPACE_ID" VARCHAR(255) NOT NULL,
    "TYPE_ID" VARCHAR(255) NOT NULL
);
CREATE CACHED TABLE "PUBLIC"."API_RESPONSE_TEMPLATE"(
    "APIID" VARCHAR(255) NOT NULL,
    "RESPONSE_ID" VARCHAR(255) NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "TEMPLATE_ID" VARCHAR(255),
    "TYPE" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."API_REQUEST_TEMPLATE"(
    "APIID" VARCHAR(255) NOT NULL,
    "REQUEST_ID" VARCHAR(255) NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "TEMPLATE_ID" VARCHAR(255),
    "TYPE" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."API_REPO"(
    "APIDOC_ID" VARCHAR(255) NOT NULL,
    "APIID" VARCHAR(255) NOT NULL,
    "ENDPOINT_ID" VARCHAR(255) NOT NULL,
    "METHOD" VARCHAR(255) NOT NULL,
    "PID" VARCHAR(255) NOT NULL,
    "URL" VARCHAR(255) NOT NULL,
    "API_NAME" VARCHAR(255),
    "DESC" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."API_QUERY_PARAM"(
    "APIID" VARCHAR(255) NOT NULL,
    "PARAM_ID" VARCHAR(255) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "MANDATORY" BOOLEAN NOT NULL,
    "PARAM_NAME" VARCHAR(255),
    "PARAM_TYPE" VARCHAR(255),
    "TEMPLATE" VARCHAR(255),
    "DEFAULTVALUE" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."API_PATH_PARAM"(
    "APIID" VARCHAR(255) NOT NULL,
    "PARAM_ID" VARCHAR(255) NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "PARAM_NAME" VARCHAR(255),
    "PARAM_TYPE" VARCHAR(255),
    "TEMPLATE" VARCHAR(255)
);
CREATE CACHED TABLE "PUBLIC"."API_HEADER_PARAM"(
    "APIID" VARCHAR(255) NOT NULL,
    "PARAM_ID" VARCHAR(255) NOT NULL,
    "DEFAULTVALUE" VARCHAR(255),
    "DESCRIPTION" VARCHAR(255),
    "MANDATORY" BOOLEAN NOT NULL,
    "PARAM_NAME" VARCHAR(255),
    "PARAM_TYPE" VARCHAR(255),
    "TEMPLATE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("UID");
ALTER TABLE "PUBLIC"."TYPE_ELEMENT" ADD CONSTRAINT "PUBLIC"."UKM7YF2UKF53GSCBM1H54AAKLR9" UNIQUE("TYPE_ID", "NAMESPACE_ID", "SL_NO", "ELEMENT_NAME");
ALTER TABLE "PUBLIC"."TYPE_ELEMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_EB" PRIMARY KEY("NAMESPACE_ID", "SL_NO", "TYPE_ID");
ALTER TABLE "PUBLIC"."TYPESREPO" ADD CONSTRAINT "PUBLIC"."UKETV23WNB4WFUGMY1IH3TUA02K" UNIQUE("NAMESPACE_ID", "TYPE_NAME");
ALTER TABLE "PUBLIC"."TYPESREPO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C6" PRIMARY KEY("NAMESPACE_ID", "TYPE_ID");
ALTER TABLE "PUBLIC"."TEMPLATE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("TEMPLATE_ID");
ALTER TABLE "PUBLIC"."SWAGGER_SPEC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID", "PID");
ALTER TABLE "PUBLIC"."SIMPLE_TYPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2D" PRIMARY KEY("NAMESPACE_ID", "TYPE_ID");
ALTER TABLE "PUBLIC"."REFFERED_TEMPLATE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("REFFERED_TEMPLATE_ID", "TEMPLATE_ID");
ALTER TABLE "PUBLIC"."NAMESPACEREP" ADD CONSTRAINT "PUBLIC"."UKST7JQ43VJCHP292VM6O2PW0IJ" UNIQUE("NAMESPACE_URL");
ALTER TABLE "PUBLIC"."NAMESPACEREP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3F" PRIMARY KEY("NAMESPACE_ID");
ALTER TABLE "PUBLIC"."FILE_EXPLORER" ADD CONSTRAINT "PUBLIC"."FKQ4A9S0YYY74M8WAN2MY0ESSFN" FOREIGN KEY("PARENT_ID", "PID") REFERENCES "PUBLIC"."FILE_EXPLORER"("ID", "PID") NOCHECK;
ALTER TABLE "PUBLIC"."FILE_EXPLORER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID", "PID");
ALTER TABLE "PUBLIC"."FAVOURITE" ADD CONSTRAINT "PUBLIC"."FKI0F6YLK0EWQ8INUQOWQE39KRW" FOREIGN KEY("ITEMID", "PID") REFERENCES "PUBLIC"."FILE_EXPLORER"("ID", "PID") NOCHECK;
ALTER TABLE "PUBLIC"."FAVOURITE" ADD CONSTRAINT "PUBLIC"."FK4NNYDXDRA1X6Y9AAXYGL0AKHU" FOREIGN KEY("FILE_DETAILS_ID", "FILE_DETAILS_PID") REFERENCES "PUBLIC"."FILE_EXPLORER"("ID", "PID") NOCHECK;
ALTER TABLE "PUBLIC"."FAVOURITE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3B" PRIMARY KEY("ITEMID", "PID", "USERID");
ALTER TABLE "PUBLIC"."COMPLEX_TYPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("NAMESPACE_ID", "TYPE_ID");
ALTER TABLE "PUBLIC"."API_RESPONSE_TEMPLATE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7D" PRIMARY KEY("APIID", "RESPONSE_ID");
ALTER TABLE "PUBLIC"."API_REQUEST_TEMPLATE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_99" PRIMARY KEY("APIID", "REQUEST_ID");
ALTER TABLE "PUBLIC"."API_REPO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("APIDOC_ID", "APIID", "ENDPOINT_ID", "METHOD", "PID", "URL");
ALTER TABLE "PUBLIC"."API_QUERY_PARAM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C4" PRIMARY KEY("APIID", "PARAM_ID");
ALTER TABLE "PUBLIC"."API_PATH_PARAM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_EE" PRIMARY KEY("APIID", "PARAM_ID");
ALTER TABLE "PUBLIC"."API_HEADER_PARAM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("APIID", "PARAM_ID");